/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.abstractj.kalium;

public class crypto_generichash_state {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected crypto_generichash_state(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(crypto_generichash_state obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SodiumJNI.delete_crypto_generichash_state(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setH(SWIGTYPE_p_unsigned_long_long value) {
    SodiumJNI.crypto_generichash_state_h_set(swigCPtr, this, SWIGTYPE_p_unsigned_long_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long_long getH() {
    long cPtr = SodiumJNI.crypto_generichash_state_h_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long_long(cPtr, false);
  }

  public void setT(SWIGTYPE_p_unsigned_long_long value) {
    SodiumJNI.crypto_generichash_state_t_set(swigCPtr, this, SWIGTYPE_p_unsigned_long_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long_long getT() {
    long cPtr = SodiumJNI.crypto_generichash_state_t_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long_long(cPtr, false);
  }

  public void setF(SWIGTYPE_p_unsigned_long_long value) {
    SodiumJNI.crypto_generichash_state_f_set(swigCPtr, this, SWIGTYPE_p_unsigned_long_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long_long getF() {
    long cPtr = SodiumJNI.crypto_generichash_state_f_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long_long(cPtr, false);
  }

  public void setBuf(short[] value) {
    SodiumJNI.crypto_generichash_state_buf_set(swigCPtr, this, value);
  }

  public short[] getBuf() {
    return SodiumJNI.crypto_generichash_state_buf_get(swigCPtr, this);
  }

  public void setBuflen(int value) {
    SodiumJNI.crypto_generichash_state_buflen_set(swigCPtr, this, value);
  }

  public int getBuflen() {
    return SodiumJNI.crypto_generichash_state_buflen_get(swigCPtr, this);
  }

  public void setLast_node(short value) {
    SodiumJNI.crypto_generichash_state_last_node_set(swigCPtr, this, value);
  }

  public short getLast_node() {
    return SodiumJNI.crypto_generichash_state_last_node_get(swigCPtr, this);
  }

  public crypto_generichash_state() {
    this(SodiumJNI.new_crypto_generichash_state(), true);
  }

}
