package eu.artemisc.strodium;

import org.abstractj.kalium.Sodium;

/**
 * Strodium is an abstract class with static methods. It is an attempt to
 * simplify the API generated by SWIG to a more Java-ish version, as well as add
 * some proper JavaDocs to the methods.
 *
 * All method calls are wrappers around calls to JNI implemented methods. The
 * library is aimed specifically at the android platform.
 *
 * @author Jan van de Molengraft [jan@artemisc.eu]
 */
public final class Strodium {
    private Strodium() {}

    private void runInit() {
        if (Sodium.sodium_init() == -1) {
            throw new RuntimeException("StrodiumInit: could not initialize Sodium library");
        }
    }

    static {
        System.loadLibrary("kaliumjni");
    }


    /**
     * Strodium constructor should be called once per application, or at least
     * before any class is used that requires the native methods to be
     * available.
     */
    public static void StrodiumInit() {
        new Strodium().runInit();
    }
}

